### PR TITLE
Upgrade Shopify CLI, add checkout app permissions, update README

### PR DESCRIPTION
**Pull request by masonmcelvain**
## QA

- The app should build with no errors using `pn dev` .
- The README should link to the correct locations.
- We can verify that the app is being used by the dev store by confirming that the "Codice Fiscale" field renders on the first page of checkout.
- If you try to view the app in Shopify Admin, nothing will render like in the screenshot below.

image
https://ifixit-checkout-ui-extension-test.myshopify.com/admin/apps/ifixit-checkout-ui-extensions-2

### CODE REVIEW

**Comment by masonmcelvain** [comment]
dev_block 👍🏻 @deltuh-vee not quite ready yet, sorry

**Comment by masonmcelvain** [comment]
un_dev_block 👍🏻

**Comment by deltuh-vee** [comment]
dev_block ✊ 
Are the first two links that were added to the README correct?
CleanShot 2024-01-29 at 12 40 37@2x

I get this error page when visiting them.
CleanShot 2024-01-29 at 12 39 42@2x

**Comment by masonmcelvain** [comment]
> Are the first two links that were added to the README correct?

Yes, I think you may not be a member in shopify partners. I just sent you an invite.

> I also don't see the Codice Fiscale field on the first page of checkout

Which of these links did you clink so I can debug? I see "Codice Fiscale" when I click any of the "Extension target" links.

image

image

**Comment by deltuh-vee** [comment]
> Which of these links did you clink so I can debug?

Oh I got to checkout by previewing the theme and trying to checkout with an item.

**Comment by masonmcelvain** [comment]
> > Which of these links did you clink so I can debug?
> 
> Oh I got to checkout by previewing the theme and trying to checkout with an item.

Ah gotcha 👍🏻  For now let's use the dev server for QA.

**Comment by masonmcelvain** [comment]
un_dev_block 👍🏻

**Comment by deltuh-vee** [comment]
QA 🎬 
* The app builds with no errors using `pnpm dev`.
* The README links to the correct locations.
* The app is being used by the dev store and the "Codice Fiscale" field renders on the first page of checkout.
* Nothing renders when viewing the App in Shopify Admin.

**Comment by masonmcelvain** [comment]
QA 👍🏻 carry forward, I updated `pnpm-lock.yaml` with a diff from `pnpm dev`.

**Comment by masonmcelvain** [comment]
QA 👍🏻

**Comment by masonmcelvain** [comment]
QA 👍🏻 once more, updated the readme and dropped the unnecessary access scopes added in this PR

**Comment by masonmcelvain** [comment]
QA 👍🏻

**Comment by danielcliu-ifixit** [comment]
CR :v:

**Review by danielcliu-ifixit — APPROVED** [review]

**Pull request merged**
