### PR TITLE
upgrade: use API version 2023-7

### PR DESCRIPTION
**Pull request by rickisXP**
We've been using API version 2023-4 for checkout extensions. This version contained deprecated extension points, which caused extensions on thank you and order status to not load. Let's start using API version 2023-7 and use extension targets instead.

Summary of changes
--
- Followed upgrade docs [here](https://shopify.dev/docs/api/checkout-ui-extensions/2023-07/versioning-migration#update-the-extension-points-new-code-(react))
- Ran `pnpm install`

QA
--
We only have one checkout extension in main, which is the Codice Fiscale field. Make sure that shows up. Testing procedure in https://github.com/iFixit/checkout-ui-extensions/pull/3

### CODE REVIEW

**Comment by rickisXP** [comment]
@jordycosta make sure you're using the preview link that is generated at the very end (or press `p` when the script is running) and that should open the preview console.
image

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻 Nice job, that's a pretty annoying migration process. It looks like you did everything right

**Comment by erinemay** [comment]
When I go to https://partners.shopify.com/signup, it redirects me to https://accounts.shopify.com/signup and wants me to signup again. Have you seen this? 

image

**Comment by masonmcelvain** [comment]
I sent 2 invitations to each of you (@erinemay and @jordycosta). Accepting both of those should give you access to the dev store we're using for QA. Curtis has access too, is there anyone else in QA that I should give access to?

**Comment by erinemay** [comment]
QA 🦖 When I check out and input a CF value at checkout, it is present in the order details
image

**Pull request merged**
