### PR TITLE
Custom Fields: Add codice fiscale input

### LINKED ISSUE #2: Support codice fiscale
If the billing address country is Italy, insert a custom field after the billing address section.

<details>

image

image
https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-points-overview#supported-locations-payment
</details>

This customization should only be enabled if the EU store setting is enabled.

Should be [localizable](https://shopify.dev/docs/apps/checkout/best-practices/localizing-ui-extensions).

### PR DESCRIPTION
**Pull request by masonmcelvain**
Closes #2 

Adds an optional codice fiscale input field. When populated, it adds the Codice Fiscale value as an attribute to the order.

## QA

- Clone the repo
- `cd` into it, `nvm use`, and `pnpm install`
- `pnpm dev` will start a development server. Click the link it generates.
- The "App home" url is the dev Shopify Admin for this app.
- The "ui-extension" url will take you to a checkout/fake store
- Append the query parameter `?placement-reference=PAYMENT4` to the url ([docs](https://shopify.dev/docs/apps/checkout/best-practices/testing-ui-extensions#test-locally))
- At the payment step of checkout, you should see a "Codice Fiscale" input field.
- On shopify-v2, this field is only visible if you're billing address country is Italy. On this feature, the field is always visible.
- After completing the order, the codice fiscale should be added to the order in shopify admin under "Additional Details".

### CODE REVIEW

**Comment by deltuh-vee** [comment]
QA 🎬 
Codice Fiscale shows up on the payments page.

**Comment by deltuh-vee** [comment]
un_dev_block 👍

**Comment by masonmcelvain** [comment]
QA ✌🏻 carry over

**Review by sterlinghirsh — APPROVED** [review]
CR :zap: I think this is good. I was thinking about a few things wrt being able to access the billing addr. First, it looks like we can apply to get access to restricted info, though it will require putting our app through some review from Shopify. I'd rather not have all our updates go through that, so it may be best to create a small Codice Fiscale app that just handles this one piece. However, I figured we're not the only ones with this problem, so I looked online and found https://community.shopify.com/c/q-a-di-tipo-tecnico/codice-fiscale-campo-obbligatorio/td-p/1570279 which is in Italian but with Google Translate seemed to indicate that there might be some more native way to do it. I'm going to ask Massimo about this. I'm fine with adding this for now so we can move forward, though.

**Pull request merged**
